schedules:
  - cron: '0 5 * * 0'
    displayName: 'Weekly on Sunday at 5 AM UTC'
    branches:
      include: [main]
    always: true
    batch: true

trigger: none

pool:
  vmImage: ubuntu-latest
  
steps:
  - checkout: self
    fetchDepth: 0
  - task: dependabot@2
    inputs:
      mergeStrategy: 'squash'
      abandonUnwantedPullRequests: true
    env:
      PACKAGE_PAT: $(PackagePAT)