<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- External libraries -->
    <PackageVersion Include="Ardalis.GuardClauses" Version="5.0.0" />
    <PackageVersion Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageVersion Include="Elastic.Clients.Elasticsearch" Version="9.0.7" />
    <!-- NSwag & Related Packages -->
    <PackageVersion Include="NSwag.AspNetCore" Version="14.6.1" />
    <PackageVersion Include="NSwag.MSBuild" Version="14.6.1" />
    <PackageVersion Include="ZymLabs.NSwag.FluentValidation.AspNetCore" Version="0.7.1" />
    <!-- Azure-related -->
    <PackageVersion Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.4.0" />
    <PackageVersion Include="Azure.Identity" Version="1.17.0" />
    <PackageVersion Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <!-- Testing & Test Frameworks -->
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="MediatR" Version="12.5.0" />
    <PackageVersion Include="nunit" Version="4.4.0" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.10.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.0.0" />
    <PackageVersion Include="Respawn" Version="6.2.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="Testcontainers.MsSql" Version="4.7.0" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="9.0.9" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="AutoFixture.AutoNSubstitute" Version="4.18.1" />
    <PackageVersion Include="AutoFixture.NUnit4" Version="4.19.0" />
    <PackageVersion Include="AutoFixture.SeedExtensions" Version="4.18.1" />
    <PackageVersion Include="Microsoft.Extensions.TimeProvider.Testing" Version="9.9.0" />
    <!-- Microsoft ASP.NET Core -->
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.SpaProxy" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <!-- Microsoft Entity Framework -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9" />
    <!-- Microsoft Extensions & Hosting -->
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <!-- Playwright & SpecFlow -->
    <PackageVersion Include="Microsoft.Playwright" Version="1.57.0" />
    <PackageVersion Include="Microsoft.Playwright.NUnit" Version="1.57.0" />
    <PackageVersion Include="Reqnroll" Version="3.3.0" />
    <PackageVersion Include="Reqnroll.NUnit" Version="3.3.0" />
  </ItemGroup>
</Project>