<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SortedTunes.Web.AcceptanceTests</RootNamespace>
    <AssemblyName>SortedTunes.Web.AcceptanceTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="appsettings.*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </Content>
    <Content Include="appsettings.dev.json.tmpl">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <DependentUpon>appsettings.dev.json</DependentUpon>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Buynamics.Toolkit.AcceptanceTests" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Microsoft.Playwright.NUnit" />
    <PackageReference Include="Reqnroll" />
    <PackageReference Include="Reqnroll.NUnit" />
    <PackageReference Include="nunit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

</Project>
