// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SortedTunes.Web.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("LandedCosts")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("smoke")]
    public partial class LandedCostsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "smoke"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "LandedCosts", "Landed costs features", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "LandedCosts.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/LandedCosts.feature.ndjson", 6);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Can view the landed costs")]
        [global::NUnit.Framework.CategoryAttribute("User")]
        public async global::System.Threading.Tasks.Task CanViewTheLandedCosts()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Can view the landed costs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("the user navigates to \'cost-models/products\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
    await testRunner.AndAsync("they search for \'Test Beer (DO NOT DELETE THIS PRODUCT)\' and open the product det" +
                        "ails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.WhenAsync("the user changes the date range from January 2023 to April 2023", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
    await testRunner.AndAsync("they change the results-tab to \'Landed Costs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.AndAsync("they change the price calculation method to Median", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Title",
                            "DataTestId",
                            "Value"});
                table1.AddRow(new string[] {
                            "Total shipment",
                            "total-shipment",
                            "1000.00/UNIT"});
                table1.AddRow(new string[] {
                            "Shipping costs per unit",
                            "shipping-cost-unit",
                            "10.00/UNIT"});
                table1.AddRow(new string[] {
                            "Landed costs per unit",
                            "landed-cost-unit",
                            "34.47/UNIT"});
#line 13
    await testRunner.ThenAsync("the landed costs results shows the following values", ((string)(null)), table1, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Can view the landed costs table")]
        [global::NUnit.Framework.CategoryAttribute("User")]
        public async global::System.Threading.Tasks.Task CanViewTheLandedCostsTable()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Can view the landed costs table", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
    await testRunner.GivenAsync("the user navigates to \'cost-models/products\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
    await testRunner.AndAsync("they search for \'Test Beer (DO NOT DELETE THIS PRODUCT)\' and open the product det" +
                        "ails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.WhenAsync("they change the results-tab to \'Landed Costs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "CostComponent",
                            "Percentage",
                            "Costs"});
                table2.AddRow(new string[] {
                            "DirectMaterials",
                            "26",
                            "6"});
                table2.AddRow(new string[] {
                            "DirectLabour",
                            "9",
                            "2"});
                table2.AddRow(new string[] {
                            "ManufacturingOverhead",
                            "7",
                            "1"});
                table2.AddRow(new string[] {
                            "CostOfSales",
                            "44",
                            "10"});
                table2.AddRow(new string[] {
                            "GsaAndOtherExpenses",
                            "45",
                            "10"});
                table2.AddRow(new string[] {
                            "ProfitBeforeTax",
                            "10",
                            "2"});
                table2.AddRow(new string[] {
                            "Total",
                            "100",
                            "24"});
                table2.AddRow(new string[] {
                            "ShippingCost",
                            "31",
                            "7"});
                table2.AddRow(new string[] {
                            "TotalLandedCost",
                            "131",
                            "31"});
#line 24
    await testRunner.ThenAsync("the whats the price table shows the following results", ((string)(null)), table2, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Can view the landed costs with calculation method median")]
        [global::NUnit.Framework.CategoryAttribute("User")]
        public async global::System.Threading.Tasks.Task CanViewTheLandedCostsWithCalculationMethodMedian()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Can view the landed costs with calculation method median", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("the user navigates to \'cost-models/products\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
    await testRunner.AndAsync("they search for \'Test Beer (DO NOT DELETE THIS PRODUCT)\' and open the product det" +
                        "ails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.WhenAsync("they change the results-tab to \'Landed Costs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.AndAsync("they change the price calculation method to Median", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "CostComponent",
                            "Percentage",
                            "Costs"});
                table3.AddRow(new string[] {
                            "DirectMaterials",
                            "26",
                            "6"});
                table3.AddRow(new string[] {
                            "DirectLabour",
                            "9",
                            "2"});
                table3.AddRow(new string[] {
                            "ManufacturingOverhead",
                            "7",
                            "1"});
                table3.AddRow(new string[] {
                            "CostOfSales",
                            "44",
                            "10"});
                table3.AddRow(new string[] {
                            "GsaAndOtherExpenses",
                            "45",
                            "10"});
                table3.AddRow(new string[] {
                            "ProfitBeforeTax",
                            "10",
                            "2"});
                table3.AddRow(new string[] {
                            "Total",
                            "100",
                            "24"});
                table3.AddRow(new string[] {
                            "ShippingCost",
                            "41",
                            "10"});
                table3.AddRow(new string[] {
                            "TotalLandedCost",
                            "141",
                            "34"});
#line 43
    await testRunner.ThenAsync("the whats the price table shows the following results", ((string)(null)), table3, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Can view the landed costs with calculation method Max")]
        [global::NUnit.Framework.CategoryAttribute("User")]
        public async global::System.Threading.Tasks.Task CanViewTheLandedCostsWithCalculationMethodMax()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Can view the landed costs with calculation method Max", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
    await testRunner.GivenAsync("the user navigates to \'cost-models/products\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
    await testRunner.AndAsync("they search for \'Test Beer (DO NOT DELETE THIS PRODUCT)\' and open the product det" +
                        "ails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.WhenAsync("they change the results-tab to \'Landed Costs\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
    await testRunner.AndAsync("they change the price calculation method to Max", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "CostComponent",
                            "Percentage",
                            "Costs"});
                table4.AddRow(new string[] {
                            "DirectMaterials",
                            "26",
                            "6"});
                table4.AddRow(new string[] {
                            "DirectLabour",
                            "9",
                            "2"});
                table4.AddRow(new string[] {
                            "ManufacturingOverhead",
                            "7",
                            "1"});
                table4.AddRow(new string[] {
                            "CostOfSales",
                            "44",
                            "10"});
                table4.AddRow(new string[] {
                            "GsaAndOtherExpenses",
                            "45",
                            "10"});
                table4.AddRow(new string[] {
                            "ProfitBeforeTax",
                            "10",
                            "2"});
                table4.AddRow(new string[] {
                            "Total",
                            "100",
                            "24"});
                table4.AddRow(new string[] {
                            "ShippingCost",
                            "62",
                            "15"});
                table4.AddRow(new string[] {
                            "TotalLandedCost",
                            "162",
                            "39"});
#line 62
    await testRunner.ThenAsync("the whats the price table shows the following results", ((string)(null)), table4, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
