// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SortedTunes.Web.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("WhatsThePrice")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("smoke")]
    public partial class WhatsThePriceFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "smoke"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "WhatsThePrice", "Calculating product prices", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "WhatsThePrice.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/WhatsThePrice.feature.ndjson", 9);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Can view whats the price of simple product")]
        [global::NUnit.Framework.CategoryAttribute("User")]
        public async global::System.Threading.Tasks.Task CanViewWhatsThePriceOfSimpleProduct()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Can view whats the price of simple product", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("the user navigates to \'cost-models/products\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
    await testRunner.AndAsync("they search for \'Test Bottle (DO NOT DELETE THIS PRODUCT)\' and open the product d" +
                        "etails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.WhenAsync("the user changes the date range from January 2023 to April 2023", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
    await testRunner.AndAsync("they change the results-tab to \"What\'s the price\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "CostComponent",
                            "Percentage",
                            "Costs"});
                table5.AddRow(new string[] {
                            "DirectMaterials",
                            "13",
                            "0"});
                table5.AddRow(new string[] {
                            "DirectLabour",
                            "17",
                            "0"});
                table5.AddRow(new string[] {
                            "ManufacturingOverhead",
                            "27",
                            "0"});
                table5.AddRow(new string[] {
                            "CostOfSales",
                            "58",
                            "0"});
                table5.AddRow(new string[] {
                            "GsaAndOtherExpenses",
                            "36",
                            "0"});
                table5.AddRow(new string[] {
                            "ProfitBeforeTax",
                            "4",
                            "0"});
                table5.AddRow(new string[] {
                            "Total",
                            "100",
                            "0"});
#line 12
    await testRunner.ThenAsync("the whats the price table shows the following results", ((string)(null)), table5, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Can view whats the price of product with components")]
        [global::NUnit.Framework.CategoryAttribute("User")]
        public async global::System.Threading.Tasks.Task CanViewWhatsThePriceOfProductWithComponents()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Can view whats the price of product with components", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("the user navigates to \'cost-models/products\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.AndAsync("they search for \'Test Beer (DO NOT DELETE THIS PRODUCT)\' and open the product det" +
                        "ails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
    await testRunner.WhenAsync("the user changes the date range from January 2023 to April 2023", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.AndAsync("they change the results-tab to \"What\'s the price\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "CostComponent",
                            "Percentage",
                            "Costs",
                            "Price paid",
                            "Difference"});
                table6.AddRow(new string[] {
                            "DirectMaterials",
                            "27",
                            "6",
                            "8",
                            "1"});
                table6.AddRow(new string[] {
                            "DirectLabour",
                            "9",
                            "2",
                            "2",
                            "0"});
                table6.AddRow(new string[] {
                            "ManufacturingOverhead",
                            "7",
                            "1",
                            "2",
                            "0"});
                table6.AddRow(new string[] {
                            "CostOfSales",
                            "45",
                            "11",
                            "13",
                            "2"});
                table6.AddRow(new string[] {
                            "GsaAndOtherExpenses",
                            "44",
                            "10",
                            "13",
                            "2"});
                table6.AddRow(new string[] {
                            "ProfitBeforeTax",
                            "9",
                            "2",
                            "3",
                            "0"});
                table6.AddRow(new string[] {
                            "Total",
                            "100",
                            "24",
                            "30",
                            "5"});
#line 28
    await testRunner.ThenAsync("the whats the price table shows the following results", ((string)(null)), table6, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Can view whats the price of product with components - different date range")]
        [global::NUnit.Framework.CategoryAttribute("User")]
        public async global::System.Threading.Tasks.Task CanViewWhatsThePriceOfProductWithComponents_DifferentDateRange()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Can view whats the price of product with components - different date range", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
    await testRunner.GivenAsync("the user navigates to \'cost-models/products\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
    await testRunner.AndAsync("they search for \'Test Beer (DO NOT DELETE THIS PRODUCT)\' and open the product det" +
                        "ails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
    await testRunner.WhenAsync("the user changes the date range from January 2023 to February 2023", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
    await testRunner.AndAsync("they change the results-tab to \"What\'s the price\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "CostComponent",
                            "Percentage",
                            "Costs",
                            "Price paid",
                            "Difference"});
                table7.AddRow(new string[] {
                            "DirectMaterials",
                            "27",
                            "6",
                            "9",
                            "2"});
                table7.AddRow(new string[] {
                            "DirectLabour",
                            "9",
                            "2",
                            "3",
                            "0"});
                table7.AddRow(new string[] {
                            "ManufacturingOverhead",
                            "7",
                            "1",
                            "2",
                            "0"});
                table7.AddRow(new string[] {
                            "CostOfSales",
                            "45",
                            "10",
                            "14",
                            "3"});
                table7.AddRow(new string[] {
                            "GsaAndOtherExpenses",
                            "44",
                            "10",
                            "14",
                            "3"});
                table7.AddRow(new string[] {
                            "ProfitBeforeTax",
                            "9",
                            "2",
                            "3",
                            "0"});
                table7.AddRow(new string[] {
                            "Total",
                            "100",
                            "24",
                            "32",
                            "8"});
#line 44
    await testRunner.ThenAsync("the whats the price table shows the following results", ((string)(null)), table7, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Can view latest whats the price of product with components")]
        [global::NUnit.Framework.CategoryAttribute("User")]
        public async global::System.Threading.Tasks.Task CanViewLatestWhatsThePriceOfProductWithComponents()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Can view latest whats the price of product with components", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 55
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 56
    await testRunner.GivenAsync("the user navigates to \'cost-models/products\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 57
    await testRunner.AndAsync("they search for \'Test Beer (DO NOT DELETE THIS PRODUCT)\' and open the product det" +
                        "ails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.WhenAsync("the user changes the date range from January 2023 to April 2023", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
    await testRunner.AndAsync("they change the results-tab to \"What\'s the price\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.AndAsync("they change the price calculation method to Latest", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "CostComponent",
                            "Percentage",
                            "Costs",
                            "Price paid",
                            "Difference"});
                table8.AddRow(new string[] {
                            "DirectMaterials",
                            "28",
                            "6",
                            "7",
                            "0"});
                table8.AddRow(new string[] {
                            "DirectLabour",
                            "9",
                            "2",
                            "2",
                            "0"});
                table8.AddRow(new string[] {
                            "ManufacturingOverhead",
                            "7",
                            "1",
                            "2",
                            "0"});
                table8.AddRow(new string[] {
                            "CostOfSales",
                            "45",
                            "11",
                            "12",
                            "1"});
                table8.AddRow(new string[] {
                            "GsaAndOtherExpenses",
                            "44",
                            "10",
                            "12",
                            "1"});
                table8.AddRow(new string[] {
                            "ProfitBeforeTax",
                            "9",
                            "2",
                            "2",
                            "0"});
                table8.AddRow(new string[] {
                            "Total",
                            "100",
                            "24",
                            "28",
                            "3"});
#line 61
    await testRunner.ThenAsync("the whats the price table shows the following results", ((string)(null)), table8, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Can view the historical product prices comparison")]
        [global::NUnit.Framework.CategoryAttribute("User")]
        public async global::System.Threading.Tasks.Task CanViewTheHistoricalProductPricesComparison()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Can view the historical product prices comparison", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 72
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 73
    await testRunner.GivenAsync("the user navigates to \'cost-models/products\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 74
    await testRunner.AndAsync("they search for \'Test Beer (DO NOT DELETE THIS PRODUCT)\' and open the product det" +
                        "ails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
    await testRunner.WhenAsync("the user changes the date range from January 2023 to April 2023", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
    await testRunner.AndAsync("they change the results-tab to \"Price Discipline\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.ThenAsync("the price discipline chart shows \"purchasing-prices\" and \"price-discipline\" serie" +
                        "s", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Can view the direct materials costs in the product currency")]
        [global::NUnit.Framework.CategoryAttribute("User")]
        public async global::System.Threading.Tasks.Task CanViewTheDirectMaterialsCostsInTheProductCurrency()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Can view the direct materials costs in the product currency", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 80
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 81
    await testRunner.GivenAsync("the user navigates to \'cost-models/products\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 82
    await testRunner.AndAsync("they search for \'Test Beer (DO NOT DELETE THIS PRODUCT)\' and open the product det" +
                        "ails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.ThenAsync("the product direct material costs shows \'EUR\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Can view the direct materials costs in a different currency")]
        [global::NUnit.Framework.CategoryAttribute("User")]
        public async global::System.Threading.Tasks.Task CanViewTheDirectMaterialsCostsInADifferentCurrency()
        {
            string[] tagsOfScenario = new string[] {
                    "User"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Can view the direct materials costs in a different currency", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 86
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 87
    await testRunner.GivenAsync("the user navigates to \'cost-models/products\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
    await testRunner.AndAsync("they search for \'Test Beer (DO NOT DELETE THIS PRODUCT)\' and open the product det" +
                        "ails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
    await testRunner.WhenAsync("they change the date-control currency to \'USD\' and select \'US Dollar\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
    await testRunner.ThenAsync("the product direct material costs shows \'USD\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
