parameters:
  - name: buildConfiguration
    type: string
  - name: environmentName
    type: string
  - name: azureEnvironment
    type: string
  - name: smokeOnly
    type: boolean
    default: false

jobs:
  - deployment: "deploybackend${{parameters.environmentName}}"
    displayName: Deploy Backend
    workspace:
      clean: all
    environment: ${{parameters.azureEnvironment}}
    variables:
      - template: ../Variables/${{parameters.environmentName}}-variables.yaml
    pool:
      name: Azure
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - template: deploy-backend.yaml
              parameters:
                environmentName: ${{variables.environmentName}}
                
  - deployment: "deployfrontend${{parameters.environmentName}}"
    dependsOn: 
      - "deploybackend${{parameters.environmentName}}"
    displayName: Deploy Frontend
    workspace:
      clean: all
    environment: ${{parameters.azureEnvironment}}
    variables:
      - template: ../Variables/${{parameters.environmentName}}-variables.yaml
    pool:
      name: Azure
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - template: deploy-frontend.yaml
              parameters:
                environmentName: ${{variables.environmentName}}

  - job: "refresh${{parameters.environmentName}}"
    dependsOn: 
      - "deploybackend${{parameters.environmentName}}"
      - "deployfrontend${{parameters.environmentName}}"
    displayName: Refresh Test Products
    variables:
      - template: ../Variables/${{parameters.environmentName}}-variables.yaml
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: refresh.yaml
        parameters:
          environment: ${{variables.environmentName}}
          command: refresh-test-products

  - job: "acceptancetests${{parameters.environmentName}}"
    displayName: Acceptance Tests
    dependsOn: 
      - "deploybackend${{parameters.environmentName}}"
      - "deployfrontend${{parameters.environmentName}}"
      - "refresh${{parameters.environmentName}}"
    workspace:
      clean: all
    variables:
      - template: ../Variables/${{parameters.environmentName}}-variables.yaml
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: acceptance-tests.yaml
        parameters:
          buildConfiguration: ${{parameters.buildConfiguration}}
          environmentName: ${{variables.environmentName}}
          smokeOnly: ${{parameters.smokeOnly}}
