<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SortedTunes.Domain.SpecimenBuilders</RootNamespace>
    <AssemblyName>SortedTunes.Domain.SpecimenBuilders</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture.AutoNSubstitute" />
    <PackageReference Include="AutoFixture.NUnit4" />
    <PackageReference Include="AutoFixture.SeedExtensions" />
    <PackageReference Include="NUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
